export const SLIDE_TYPES = [
  { value: 'cover',      label: 'Cover' },
  { value: 'text',       label: 'Quote / Statement' },
  { value: 'longtext',   label: 'Big Statement' },
  { value: 'list',       label: 'Numbered List' },
  { value: 'doublelist', label: 'Double List' },
  { value: 'imagetext',  label: 'Photo + Text' },
  { value: 'textimage',  label: 'Text + Side Photo' },
  { value: 'cta',        label: 'CTA / Outro' },
  { value: 'code',       label: 'Code Snippet' },
  { value: 'screenshot', label: 'Screenshot' },
  { value: 'framed',     label: 'Framed Image' },
];

export const CODE_LANGUAGES = [
  'javascript', 'typescript', 'python', 'jsx', 'tsx',
  'css', 'html', 'bash', 'json', 'rust', 'go', 'sql',
];

export const BULLETS_ICONS = ['①', '②', '③', '④', '⑤'];

export function createSlide(type = 'cover') {
  const defaults = {
    cover: {
      heading: 'Your Main Heading',
      subtitle: 'A compelling subtitle goes right here',
      tag: '',
      body: '',
      bullets: [],
      bullets2: [],
      ordinal2: '',
      heading2: '',
      code: '',
      language: 'javascript',
      imageUrl: null,
      caption: '',
    },
    text: {
      heading: "Boundaries aren't optional",
      subtitle: '',
      tag: 'SERIES NAME',
      body: 'Burnout taught me one thing:',
      bullets: [],
      bullets2: [],
      ordinal2: '',
      heading2: '',
      code: '',
      language: 'javascript',
      imageUrl: null,
      caption: '',
    },
    longtext: {
      heading: 'Here are 5 that changed everything!',
      subtitle: '',
      tag: 'SERIES NAME',
      body: '',
      bullets: [],
      bullets2: [],
      ordinal2: '',
      heading2: '',
      code: '',
      language: 'javascript',
      imageUrl: null,
      caption: '',
    },
    list: {
      heading: 'Define Work Hours',
      subtitle: 'One',
      tag: 'SERIES NAME',
      body: '',
      bullets: [
        'Stop treating "flexible" as "always available"',
        'Pick clear start & end times',
        'Communicate them upfront',
      ],
      bullets2: [],
      ordinal2: '',
      heading2: '',
      code: '',
      language: 'javascript',
      imageUrl: null,
      caption: '',
    },
    doublelist: {
      heading: 'Protect Deep Focus',
      subtitle: 'Two',
      tag: 'SERIES NAME',
      body: '',
      bullets: [
        'Block 1–2 hours daily for priority work',
        'Silence notifications',
        'Say no to "just a quick chat" during this block',
      ],
      ordinal2: 'Three',
      heading2: 'Limit Meetings',
      bullets2: [
        'Only accept meetings with clear purpose',
        'Suggest async updates when possible',
        'Cap your weekly meeting hours',
      ],
      code: '',
      language: 'javascript',
      imageUrl: null,
      caption: '',
    },
    imagetext: {
      heading: 'Build Device-Free Zone',
      subtitle: 'Four',
      tag: 'SERIES NAME',
      body: '',
      bullets: [
        'No laptop at meals',
        'No phone in bed',
        'Short offline breaks = long-term clarity',
      ],
      bullets2: [],
      ordinal2: '',
      heading2: '',
      code: '',
      language: 'javascript',
      imageUrl: null,
      caption: '',
    },
    textimage: {
      heading: 'Recharge Without Guilt',
      subtitle: 'Five',
      tag: 'SERIES NAME',
      body: '',
      bullets: [
        'Schedule rest the same way you work',
        'Exercise, walks, hobbies count as productivity',
        'Rest is not a reward — it\'s maintenance',
      ],
      bullets2: [],
      ordinal2: '',
      heading2: '',
      code: '',
      language: 'javascript',
      imageUrl: null,
      caption: '',
    },
    cta: {
      heading: "Save this post if it's helpful!",
      subtitle: '',
      tag: '',
      body: 'Follow for more tips!',
      bullets: [],
      bullets2: [],
      ordinal2: '',
      heading2: '',
      code: '',
      language: 'javascript',
      imageUrl: null,
      caption: '',
    },
    code: {
      heading: 'Code Example',
      subtitle: '',
      tag: 'Code',
      body: '',
      bullets: [],
      bullets2: [],
      ordinal2: '',
      heading2: '',
      code: 'function greet(name) {\n  return `Hello, ${name}!`;\n}\n\nconsole.log(greet("World"));',
      language: 'javascript',
      imageUrl: null,
      caption: '',
    },
    screenshot: {
      heading: '',
      subtitle: '',
      tag: '',
      body: '',
      bullets: [],
      bullets2: [],
      ordinal2: '',
      heading2: '',
      code: '',
      language: 'javascript',
      imageUrl: null,
      textAbove: '',
      caption: 'Caption text goes here',
    },
    framed: {
      heading: '',
      subtitle: '',
      tag: '',
      body: '',
      bullets: [],
      bullets2: [],
      ordinal2: '',
      heading2: '',
      code: '',
      language: 'javascript',
      imageUrl: null,
      textAbove: '',
      caption: 'Caption goes here',
      captionPosition: 'below',
      imageSize: 75,
    },
  };

  return {
    id: crypto.randomUUID(),
    type,
    ...(defaults[type] ?? defaults.text),
  };
}
